version: "3"
services:
  database:
    image: postgres:12-alpine
    container_name: taxi-database
    environment: 
      POSTGRES_PASSWORD: 123456
    volumes:
     - taxi-database:/var/lib/postgresql/data
    ports:
     - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: always
volumes:
  taxi-database:
