spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    name: jdbc/datasource
    url: jdbc:postgresql://localhost:5432/taxi_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    platform: POSTGRESQL
    validationQuery: SELECT 1
    hikari:
      connection-timeout: 20000 #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 10 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 10 #maximum pool size
      idle-timeout: 10000 #maximum idle time for connection
      max-lifetime: 1000 # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      auto-commit: true #default auto-commit behavior.
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate.max_fetch_depth: 1
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  path: /tmp/logs
  file:
    max-size: 10MB

